### ISSUE TITLE
Add commit message convention to CONTRIBUTING.md

### ISSUE THREAD

**Issue by ddeboer** [portphp/boilerplate#3]
Imperative, so `Fix #1`; not `Fixes #1` or `Fixed #1`.

**Comment by sagikazarmark** [comment]
I vote for option 2. I always write commit messages as they seem to be a third person. So that the messages can answer the 'What does this commit do?' question.

This logic seemed always helpful, for example in tests as well. (phpspec: it_accepts_a_parameter).

**Comment by ddeboer** [comment]
The message should indeed answer that question.

However, this is not up for vote. It will be the first option, the imperative. For an explanation, see http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html and https://about.gitlab.com/2014/09/29/gitlab-flow/.

**Comment by sagikazarmark** [comment]
Makes sense.

**Comment by sagikazarmark** [comment]
I guess I am gonna have to get used to it. Hard thing, sorry in advance for the first X mistakes. :stuck_out_tongue_winking_eye:
