### ISSUE TITLE
Note about squashing commits

### ISSUE THREAD

**Issue by sagikazarmark** [portphp/boilerplate#5]
In the last few years I experienced that a lot of people ask to squash commits in a PR. Even in my CONTRIBUTION documents I have this requirement.

However some experience showed me that in some cases it is simply not necessary or even bad.

In some cases, it is good know what stages a feature implementation went through. While the CONTRIBUTION docs says 'squash when asked', maybe we should not make it a general requirement.

WDYT?

**Comment by ddeboer** [comment]
I like to leave it in there, so that when a contributor commits like 20 ‘fix my mistake’ commits and we ask him/her to squash commits, we have explained how.

Or do you mean that we shouldn’t automatically ask contributors to squash in their PRs?

**Comment by sagikazarmark** [comment]
Didn't suggest to remove it, it is good there. But we could add a 'While it
is not a general requirement, when asked...' clause.

**Comment by ddeboer** [comment]
I like to keep such docs as short as possible (to prevent TL;DR syndrome). To me, ‘when asked’ means: you don’t have to do so by yourself, but only in case we ask you to.

**Comment by sagikazarmark** [comment]
Fair enough, it means it to me as well. It was a "Just for the case of "
comment. :wink:

**Comment by ddeboer** [comment]
Heh, no problem. It’s very valuable when people read the docs carefully and comment on them.
